name: frontend CI/CD
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        react-version: 18.13.0
    - name: Install pnpm
      run: |
        npm install -g pnpm
    - name: Install dependencies
      run: |
        pnpm install
    - name: Lint with eslint
      run: |
        pnpm run lint
    - name: Build Container
      run: |
        docker build -t rokiis1/table .